osx_image: xcode9.1
rvm: 2.2
language: objective-c
cache:
- cocoapods
- bundler
before_install:
- gem install bundler
install:
- bundle update
- pod repo update
script:
- sh ./fastlane/decrypt_p12.sh
- fastlane beta
notifications:
  slack: yumimobi:wCaD46mZfHIPfiI6guogLeWB
env:
  global:
  - secure: LZf9MlvotDSj13YBekKcjaDxbmTJmFychu8YXjd/qjbv+rH1Zd07G8gdWf21c+zgBjv5iShm8QPt9MtJWx6zC8M2/qZj1ryw5fTWZJchbYEiiWWTXtlnbXSxRYUXL9xHGMrcBmvRkj9Dn52PwYCE7SmdmhaQnL6CGmbE8RKAudmsw03Cw1DVf0Bcha2XAZ4M7iVeU6hDsEPF5lvZF6BM5mzsLJGGtvbD79g45UidvK8zd3S7jEpK2XsAfEF0FxVKfpGj39e23KjzwZnYrSllqOGcE6infvQ7lclSnbKuENz/aIq1k6iVCGdEXpr2lg8mXlQnq81OKu70zPZ7egvnubm8Jre32VJj5PoljCEf5ueD58SodvBWKOY+4RO4/GLXWeALjLTCe8Fw668blTGXtYy8CUyU79yaAwLk4r4fz7V8gWPalXkwHqxjS1bye208777KKeyMB1ztFGuM/MLrrIN4wVT+fMngxQ8vWQisZ20fQujh23JJOBKOPT9RMHz83ZD6j95Fzd/9Svakq3CL4iGZ8eR4hwonqLTFnWSoPTN2a96XX33S36+VQaCR0baX4WiJUh41KznYVdlTrrGmhUsc9A1NqEGM1odBr9qhiJX0jvOJ1Ava93fI3XfOXIxFyZ1IGLvMbVX1vJ8a9uGFVmiTnIzpSOu/dzDOEBytAnE=
  - secure: uhnhKQUZRvF9reLnCpwkKEbR3n5yfFpObzWgSXDx0KKD+I52hdnAIWpHpEcdCRF5/CGCBzKabv+gBr0+Iv62oXxTEhoqxhrfRhe7B0jZM/s0V9aHGnpVVfvr+vac8gPakH+GZmSwB+d6kP5BinCctbvLs+vjuxTiT0hm/I+anr4L7C/0lPLBspJRwe1QpvibgeMHTpkLrGjaGwzeZxYg7ofMlID3fv09ctOZ5XLvRciczes2xWP3tZAMzujN5C0F6SyYhcI9PBQ1VZXTsPpltu9ZzMAy0QiwDiEFOUqAbRPWBz8LLVWHfOrZ6rOoczux7goDPdUndfhCQ0PLMI6E26Etd0vy0N0HcRipr3VCtOeckYWQwOddiLS5BD1B0NMUZuzuJaV5r9tOo9WEo6oFgOy/qcTj1i/1QiaWb0hn93mcwIeVIGvJYiUxk5GyMnuTJrqmtRTI14H43VYWdugVw9JBytTw2bt2onzVD4ZcIut9CBxDu1TRNvZwzNh03Z571WFVyzW+HbZHfONSLEZeQTVBtft6j93qzxD4Z418HzDnsT4n02Fbjb+Cob95MU/qiNCH6xMnkE2OV0DvrnDLPKJdhxxzj/9mmsBa/464cdl/X6QoeWpY/Z4aW6iltFtT2aKdEi3cfqVm2+wjBJB5WVSijw+eJGyNeQ66m/6ylcg=
  - secure: vMGWcGcsYARwyn31k0gIEjk5oVvT4NLeZSon0u+GzjjxY0Ww9bryer8xp23jwYYutfarzJavUMZnwJZuGxLA9CbE+FkSrAHYnX7tvylM8Z4Isx9d8sc9r+6Fz/8TYhftV2o3i6/D3Qdp/ScGL1ot/CiulKUUKWqqtHjhW4g9bRyC8HSs/Po2/ufxlLm3UQ7qlGGleBuCG58uIlWZpSYKiD2oxJg12ipxpTvLsRfgzqIywkTtZ6WWqyGPACgPgJRYwzEAe4UOA3Boyydqa9R52Bu37GfofglqBsSrzF4MKLSGQY4+GKyC9Kga5oQ1GhTTVGU2csB3ZDc2kZsrzYXcRmWcrox7/ZzZasxvlFBBuB1UQqHItOyn3/MttI5Pp/YMXDPnycA5n3H31csvdhruY1mioZ/4GtITfSQ1OdwajxZzGGr3CZ4u4ZfHTpc3og9NLG3p+bCu0Rk+zaXoISYtxZUt/0wp3/thKZj6/JXWT7BlcO0JWo+OE3r7kt7MV9Ac/biuUF0KC5uwhst4hdYEF7SxiI15V9EQzYeUjH9L8sVutiXYDtaDepDF/K1CQfkxop9BtZBLnXNfoy87x6QtRubS8aeHH3oNaNvBJ6E5dLLIRfzFO4AuSgvHfPNlIrBey528aNkHi6+FfDAJgtp/7YAgC0IZYJCoOnPDoBxFzB8=
